const mensGS = [
    "Bitner Owen[1]",
    "Ma Jake[2]",
    "Tjhin Joshua",
    "Fung Josiah_Christian[2]",
    "Wang Tony",
    "Ye Brian",
    "Zheng Lin[4]",
    "Yim Ashton[3]",
    "Thio Julian[2]",
    "Yu Elijah_Jordan_Dizon",
    "Sun Nicholas[1]",
    "Chao Nathan",
    "Lu Dazhi",
    "Wang Derek",
    "Ambrose Elijah",
    "Land Preston",
    "Gao Bryan[3]",
    "Wu Ashton",
    "Yang Nianjin[2]",
    "Wong Brendan[2]",
    "Kono Shoma[1]",
    "Lee Ryan",
    "Sahertian Paul",
    "Ly Nathan[1]",
    "Lou Justin[2]",
    "Liu Shangshang[1]",
    "Yang Chien-Mu",
    "Chen Shaun[3]",
    "Chen Kevin",
    "Che Ethan[3]",
    "Candra Jayden[3]",
    "Payumo Jonathan[3]",
    "Emmert Alex",
    "Shultz Ball_Sage",
    "Gao Sen",
    "Huang Ryan[1]",
    "Zhou Zheng",
    "Zheng Nathan[4]",
    "Briones Zachary[2]",
    "Burns Seth"
  ];

  export default mensGS
  